[package]
name = "glissando-synth"
version = "0.1.0"
authors = ["Rodrigo García <yo@rodrigogarcia.me>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[target.'cfg(target_arch = "x86_64")'.dependencies]
vst = "0.1.0"

[target.'cfg(target_arch = "wasm32")'.dependencies]
wasm-bindgen = "0.2"